export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const GET_DATE = 'GET_DATE';
export const GET_DATE_REQUEST = 'GET_DATE_REQUEST';
export const GET_DATE_SUCCESS = 'GET_DATE_SUCCESS';
export const GET_DATE_FAILURE = 'GET_DATE_FAILURE';

export const SET_USER_AGENT = 'SET_USER_AGENT';
export const SET_USER_LANGUAGE = 'SET_USER_LANGUAGE';

export const LOAD_INTL_MESSAGES = 'LOAD_INTL_MESSAGES';
